"""Write docs/data.md: what the prepared datasets contain, generated from the files."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from first_reply.config import ROOT
from first_reply.data import techqa, tickets

CARD = ROOT / "docs" / "data.md"


def _table(df: pd.DataFrame) -> str:
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join([str(df.index.name or ""), *cols]) + " |"]
    lines.append("|" + "---|" + "---:|" * len(cols))
    for idx, row in df.iterrows():
        cells = [f"{v:,}" if isinstance(v, int) else str(v) for v in row.tolist()]
        lines.append("| " + " | ".join([str(idx), *cells]) + " |")
    return "\n".join(lines)


def _counts(df: pd.DataFrame, rows: str, cols: str) -> pd.DataFrame:
    t = df.groupby([rows, cols]).size().unstack(fill_value=0)
    t["total"] = t.sum(axis=1)
    t = t.sort_values("total", ascending=False)
    t.columns.name = None
    return t.astype(int)


def render(t: pd.DataFrame, docs: pd.DataFrame, q: pd.DataFrame, r: pd.DataFrame) -> str:
    split_order = ["train", "dev", "test"]
    by_split = _counts(t, "split", "lang").reindex(split_order)
    q_split = (
        q.groupby("split")
        .agg(questions=("qid", "size"), answerable=("answerable", "sum"))
        .reindex(split_order)
        .astype(int)
    )
    gold = q[q.answerable].gold_doc_ids.map(len).value_counts().sort_index()
    doc_types = docs.groupby("doc_type").agg(
        documents=("doc_id", "size"), median_chars=("chars", "median")
    )
    doc_types = doc_types.sort_values("documents", ascending=False).astype(int)
    supported = r.supported.mean()
    fam = t.family.value_counts()
    lang_table = pd.crosstab(t.language, t.lang)
    lang_table.index.name = "labelled / detected"
    lang_table.columns.name = None
    return f"""# Data

Generated by `first-reply data-card` from the prepared files. Both sources are pinned to a
Hugging Face commit and checked by SHA-256 (`src/first_reply/data/download.py`).

## Support tickets

[Tobi-Bueck/customer-support-tickets](https://huggingface.co/datasets/Tobi-Bueck/customer-support-tickets),
CC BY-NC 4.0. The tickets are **synthetic**: generated emails with a queue, priority, type,
tags and an agent answer. They are used for routing; their answers are generic templates and are
not used as a knowledge source.

The two labelled releases are merged (v5, then v4). v5 repeats 8,399 v4 tickets verbatim with
identical labels, so duplicates are removed on the normalised body **before** splitting.
Result: **{len(t):,} unique tickets**.

### Paraphrase families

The generator also wrote several rewordings and translations of each seed ticket. With a random
split, 40% of test tickets have a training ticket with bge-m3 cosine similarity >= 0.95, and
99% of those share the queue label, so a nearest-neighbour router looks far better than it is.
Tickets are therefore grouped into families (connected components of pairs with similarity
>= 0.90; pairs at 0.90 are still paraphrases or translations) and the split is drawn over
families: **{len(fam):,} families**, {int((fam == 1).sum()):,} of them single tickets, the
largest {fam.max():,} tickets. The assignment ships as
`src/first_reply/data/ticket_families.csv.gz` (`first-reply families` recomputes it).

### Language

The dataset's language column is unreliable: a quarter of the tickets labelled German are
written in English. Language is detected from function words instead; results are reported by
detected language.

{_table(lang_table)}

### Splits

70/10/20 over families, stratified on queue x detected language. Fixed stratified subsets of
{tickets.LLM_SUBSET["dev"]} dev and {tickets.LLM_SUBSET["test"]:,} test tickets are used for the
slower LLM runs.

{_table(by_split)}

### Queues

{_table(_counts(t, "queue", "lang"))}

### Priority and type

{_table(_counts(t, "priority", "lang"))}

{_table(_counts(t, "type", "lang"))}

## Knowledge base

TechQA from [RAGBench](https://huggingface.co/datasets/galileo-ai/ragbench), CC BY 4.0: real
questions from IBM's developer forums, each with five candidate IBM support documents. The
candidates of all questions are pooled into one corpus of **{len(docs):,} documents**, so the
other questions' documents act as distractors.

A document is relevant to a question when RAGBench marks at least one of its sentences as
relevant. These labels come from GPT-4, not from people, and only cover each question's own five
candidates; a relevant document elsewhere in the corpus counts as a miss.

{_table(doc_types)}

RAGBench lists each question twice, with two generated responses. Unique questions, kept in their
earliest split:

{_table(q_split)}

Answerable questions by number of relevant documents:
{", ".join(f"{k}: {v}" for k, v in gold.items())}.
The {int((~q.answerable).sum())} questions without a relevant document test whether the system
declines and hands over instead of answering.

### Reference responses

{len(r):,} responses from two commercial models, each labelled by GPT-4 as fully supported by
the documents or not ({supported:.1%} supported). They are used only to check how well our own
faithfulness judge agrees with those labels.
"""


def write(path: Path = CARD) -> Path:
    text = render(
        tickets.load(), techqa.load_docs(), techqa.load_questions(), techqa.load_responses()
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
